name: Build AdGuard list

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Convert
        run: |
          set -euo pipefail
          curl -fsSL https://raw.githubusercontent.com/UnRKN/ru-blocklist/refs/heads/main/ru-blocklist-ext.txt -o src.txt
          [ "$(wc -l < src.txt)" -gt 100 ]  # sanity check
          {
            echo "! Title: RU blocklist (AdGuard Home)"
            tr -d '\r' < src.txt | sed '/^[[:space:]]*$/d; s/.*/||&^/'
          } > ru-blocklist-adguard.txt
          rm src.txt
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ru-blocklist-adguard.txt
          git diff --cached --quiet && exit 0
          git commit -m "chore: update list"
          git push
